server:
  port: 0 # Use of dynamic port -> it will be automatically fetch and generate port numbers
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/todoDB
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'